import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import { SkipLink } from "@/components/skip-link";
import { LiveRegion } from "@/components/a11y/live-region";
import { UserProvider } from "@/lib/context/user-context";
import { NetworkProvider } from "@/lib/network-context";
import { OfflineIndicator } from "@/components/ui/offline-indicator";
import { ClientDebugPanel } from "@/components/dev/client-debug-panel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
          (function() {
            try {
              const persistedTheme = localStorage.getItem('theme');
              const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              
              if (persistedTheme === 'dark' || (persistedTheme === null && systemPrefersDark)) {
                document.documentElement.classList.add('dark');
              } else {
                document.documentElement.classList.remove('dark');
              }
            } catch (e) {
              console.warn('Failed to initialize theme:', e);
            }
          })();
        `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col no-horizontal-overflow`}
      >
        <ClerkProvider>
          <NetworkProvider>
            <UserProvider>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                {/* Screen reader announcements live region */}
                <LiveRegion id="a11y-announcer" politeness="polite" />

                {/* Authentication-specific announcer */}
                <LiveRegion id="a11y-announcer-assertive" politeness="assertive" />

                {/* Skip link for keyboard users */}
                <SkipLink />

                {/* Accessible toast notifications */}
                <Toaster />

                {/* Offline status indicator */}
                <OfflineIndicator />

                {/* Development-only debug panel */}
                {process.env.NODE_ENV === 'development' && <ClientDebugPanel />}

                {/* Header with landmark role */}
                <Header />

                {/* Main content with id for skip link target */}
                <main id="main-content" className="flex-1" tabIndex={-1}>
                  {children}
                </main>

                {/* Footer with landmark role */}
                <Footer />
              </ThemeProvider>
            </UserProvider>
          </NetworkProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
